E_Commerce/Models/Products.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AhmetProj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int product_id { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> brand_id { get; set; }
        public string product_name { get; set; }
        public Nullable<double> product_price { get; set; }
        public string product_description { get; set; }
        public string product_img1 { get; set; }
        public string product_img2 { get; set; }
        public string product_img3 { get; set; }
    
        public virtual Brands Brands { get; set; }
        public virtual Categorys Categorys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}

E_Commerce/Controllers/CartController.cs
using AhmetProj.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace AhmetProj.Controllers
{
    public class CartController : Controller
    {
        E_Commercemain_vtEntities db = new E_Commercemain_vtEntities();
        public Cart Sepeti_getir()
        {
            var sepetimiz = (Cart)Session["sepetimiz"];
            //session içerisinde oluşrurduğumuz sepetimiz nesnemizin adresi var
            if (sepetimiz == null)//1 kez
            {
                sepetimiz = new Cart();
                Session["sepetimiz"] = sepetimiz;
            }
            return sepetimiz;
        }

        // GET: Sepet
        public ActionResult Sepetim()
        {
            if (Session["sepetimiz"] != null)
            {
                Cart sepet = Sepeti_getir();
                List<Carts> sepetListesi = new List<Carts>();

                foreach (var item in sepet.Sepetim)
                {
                    sepetListesi.Add(new Carts { urun = item.urun, adet = item.adet });
                }

                Liste model = new Liste();
                model.carts = sepetListesi;
                return View(model);
            }
           
            else
                return RedirectToAction("Index", "Home");
        }

        public ActionResult Sepete_ekle(int? id, byte? adet)//linklede geliyor adet kutusu formatında gelecek
        {
            var _adet = adet ?? 0;
            var urun = db.Products.FirstOrDefault(x => x.product_id == id);
            if (urun != null)
            {
                Sepeti_getir().Sepete_ekle(urun, _adet);
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return RedirectToAction("Sepetim");
        }

        public ActionResult satin_al(string siparis_msj, Users users)
        {
            // Kullanıcının oturum açmış olup olmadığını kontrol et
            if ((Users)Session["user_id"] != null)
            {
                ViewBag.siparis_msj = siparis_msj;

              
                    var id = ((Users)Session["user_id"]).user_id;
                    var addresses = db.UsersAdress.Where(x => x.user_id == id).ToList();
                    ViewBag.Addresses = addresses;
                

                return View();
            }
            else
            {
                return RedirectToAction("sign_in", "UserLogin");
            }
        }

        public ActionResult sepetten_sil(int? id)
        {
            var urun = db.Products.FirstOrDefault(x => x.product_id == id);
            if (urun != null)
            {
                Sepeti_getir().Sepetten_sil(urun);
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return RedirectToAction("Sepetim");
        }
     
    }
}

E_Commerce/Controllers/ProductsController.cs
using AhmetProj.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using System.Net;

namespace AhmetProj.Controllers
{
    public class ProductsController : Controller
    {
        E_Commercemain_vtEntities db = new E_Commercemain_vtEntities();
        // GET: Products
        public ActionResult product_list()
        {
            var brands=db.Brands.ToList();
            var product=db.Products.ToList();
            Liste liste = new Liste();

         liste.brands = brands;
            liste.products= product;
            ViewBag.brand_id = new SelectList(db.Brands,"brand_id","brand_name");
          return View(liste);
        }


        [HttpPost]
        public ActionResult product_list(int? brand_id)
        {
            //Markaya gore listeleme yapıyoruz
            Liste liste = new Liste();
            if (brand_id == null)
            {
                var product = db.Products.ToList();
                liste.products = product;   
            }
            else
            {
                var brand = db.Products.Where(x => x.brand_id == brand_id).ToList();
                liste.products = brand;
            }
            ViewBag.brand_id = new SelectList(db.Brands, "brand_id", "brand_name");
            return View(liste);
        }

       

        public ActionResult product_detail(int? id)
        {


            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Burada, veritabanından verilen id değerine sahip ürünü aldık. Eğer bu ürün bulunamazsa, istenen kaynağın bulunamadığını belirten HttpNotFound sonucunu döner.
            var product = db.Products.FirstOrDefault(x => x.product_id == id);
            if (product == null)
            {
                return HttpNotFound();
            }
            //Bu kısım, Liste turunde bir nesne olusturduk ve products listesine product turunde ekliyorz. ve view a model turundeki listemizi ekliyoruz.
            var model = new Liste
            {
                products = new List<Products> { product }
            };

            return View(model);
        }
    }


}

E_Commerce/Views/Products/product_detail.cshtml
@model AhmetProj.Models.Liste
   

@{
    ViewBag.Title = "product_detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="axil-single-product-area axil-section-gap pb--0 bg-color-white">
    <div class="single-product-thumb mb--40">
        <div class="container">
            <div class="row">
                <div class="col-lg-7 mb--40">
                    @foreach (var item in Model.products)
                    {
                        <div class="row">



                            <div class="col-lg-10 order-lg-2">
                                <div class="single-product-thumbnail-wrap zoom-gallery">
                                    <div class="single-product-thumbnail product-large-thumbnail-3 axil-product">


                                        <div class="thumbnail">
                                            <a href="" class="popup-zoom">
                                                <img src="@item.product_img1" alt="Product Images">
                                            </a>
                                        </div>
                                        <div class="thumbnail">
                                            <a href="" class="popup-zoom">
                                                <img src="@item.product_img2" alt="Product Images">
                                            </a>
                                        </div>
                                        <div class="thumbnail">
                                            <a href="" class="popup-zoom">
                                                <img src="@item.product_img3" alt="Product Images">
                                            </a>
                                        </div>
                                    </div>

                                    <div class="product-quick-view position-view">
                                        <a href="" class="popup-zoom">
                                            <i class="far fa-search-plus"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="col-lg-2 order-lg-1">
                                <div class="product-small-thumb-3 small-thumb-wrapper">
                                    <div class="small-thumb-img">
                                        <img src="@item.product_img1" alt="thumb image">
                                    </div>
                                    <div class="small-thumb-img">
                                        <img src="@item.product_img2" alt="thumb image">
                                    </div>
                                    <div class="small-thumb-img">
                                        <img src="@item.product_img3" alt="thumb image">
                                    </div>

                                </div>
                            </div>
                        </div>
                    }
                    </div>
                <div class="col-lg-5 mb--40">
                    <div class="single-product-content">
                        @foreach (var item in Model.products)
                        {

                        
                        <div class="inner">
                            <h2 class="product-title">@item.product_name</h2>
                            <span class="price-amount">@item.product_price</span>
                            
                            
                            <p class="description">@item.product_description</p>

                            <!-- Start Product Action Wrapper  -->
                            <div class="product-action-wrapper d-flex-center">
                                <!-- Start Quentity Action  -->
                               
                                <!-- End Quentity Action  -->
                                <!-- Start Product Action  -->
                                <ul class="product-action d-flex-center mb--0">
                                    <li class="add-to-cart"><a href="@Url.Action("sepete_ekle","Cart",new {id=item.product_id})" class="axil-btn btn-bg-primary">Add to Cart</a></li>
                                    <li class="wishlist"><a href="wishlist.html" class="axil-btn wishlist-btn"><i class="far fa-heart"></i></a></li>
                                </ul>
                                <!-- End Product Action  -->

                            </div>
                            <!-- End Product Action Wrapper  -->
                        </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End .single-product-thumb -->

    <div class="woocommerce-tabs wc-tabs-wrapper bg-vista-white">
        <div class="container">
            <ul class="nav tabs" id="myTab" role="tablist">
                <li class="nav-item" role="presentation">
                    <a class="active" id="description-tab" data-bs-toggle="tab" href="#description" role="tab" aria-controls="description" aria-selected="true">Description</a>
                </li>

                <li class="nav-item" role="presentation">
                    <a id="reviews-tab" data-bs-toggle="tab" href="#reviews" role="tab" aria-controls="reviews" aria-selected="false">Reviews</a>
                </li>
            </ul>
            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="description" role="tabpanel" aria-labelledby="description-tab">
                    <div class="product-desc-wrapper">
                        <div class="row">
                            <div class="col-lg-6 mb--30">
                                <div class="single-desc">
                                    <h5 class="title">Specifications:</h5>
                                    <p>
                                        We’ve created a full-stack structure for our working workflow processes, were from the funny the century initial all the made, have spare to negatives. But the structure was from the funny the century rather,
                                        initial all the made, have spare to negatives.
                                    </p>
                                </div>
                            </div>
                            <!-- End .col-lg-6 -->
                            <div class="col-lg-6 mb--30">
                                <div class="single-desc">
                                    <h5 class="title">Care & Maintenance:</h5>
                                    <p>Use warm water to describe us as a product team that creates amazing UI/UX experiences, by crafting top-notch user experience.</p>
                                </div>
                            </div>
                            <!-- End .col-lg-6 -->
                        </div>
                        <!-- End .row -->
                        <div class="row">
                            <div class="col-lg-12">
                                <ul class="pro-des-features">
                                    <li class="single-features">
                                        <div class="icon">
                                            <img src="assets/images/product/product-thumb/icon-3.png" alt="icon">
                                        </div>
                                        Hızlı İade
                                    </li>
                                    <li class="single-features">
                                        <div class="icon">
                                            <img src="assets/images/product/product-thumb/icon-2.png" alt="icon">
                                        </div>
                                        Kalite Garantisi
                                    </li>
                                    <li class="single-features">
                                        <div class="icon">
                                            <img src="assets/images/product/product-thumb/icon-1.png" alt="icon">
                                        </div>
                                        Orjinal Urun
                                    </li>
                                </ul>
                                <!-- End .pro-des-features -->
                            </div>
                        </div>
                        <!-- End .row -->
                    </div>
                    <!-- End .product-desc-wrapper -->
                </div>

                <div class="tab-pane fade" id="reviews" role="tabpanel" aria-labelledby="reviews-tab">
                    <div class="reviews-wrapper">
                        <div class="row">
                           
                            <!-- End .col -->
                            <div class="col-lg-6 mb--40">
                                <!-- Start Comment Respond  -->
                                <div class="comment-respond pro-des-commend-respond mt--0">
                                    <h5 class="title mb--30">Add a Review</h5>
                                    <p>Your email address will not be published. Required fields are marked *</p>
                                    <div class="rating-wrapper d-flex-center mb--40">
                                        Your Rating <span class="require">*</span>
                                        <div class="reating-inner ml--20">
                                            <a href="#"><i class="fal fa-star"></i></a>
                                            <a href="#"><i class="fal fa-star"></i></a>
                                            <a href="#"><i class="fal fa-star"></i></a>
                                            <a href="#"><i class="fal fa-star"></i></a>
                                            <a href="#"><i class="fal fa-star"></i></a>
                                        </div>
                                    </div>

                                    <form action="#">
                                        <div class="row">
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <label>Other Notes (optional)</label>
                                                    <textarea name="message" placeholder="Your Comment"></textarea>
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-md-6 col-12">
                                                <div class="form-group">
                                                    <label>Name <span class="require">*</span></label>
                                                    <input id="name" type="text">
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-md-6 col-12">
                                                <div class="form-group">
                                                    <label>Email <span class="require">*</span> </label>
                                                    <input id="email" type="email">
                                                </div>
                                            </div>
                                            <div class="col-lg-12">
                                                <div class="form-submit">
                                                    <button type="submit" id="submit" class="axil-btn btn-bg-primary w-auto">Submit Comment</button>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                                <!-- End Comment Respond  -->
                            </div>
                            <!-- End .col -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- woocommerce-tabs -->

</div>

E_Commerce/Views/Products/product_list.cshtml
@model AhmetProj.Models.Liste
   
@{
    ViewBag.Title = "product_list";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="axil-breadcrumb-area">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 col-md-8">
                <div class="inner">
                    <ul class="axil-breadcrumb">
                        <li class="axil-breadcrumb-item"><a href="index-1.html">Anasayfa</a></li>
                        <li class="separator"></li>
                        <li class="axil-breadcrumb-item active" aria-current="page">Urunler</li>
                    </ul>
                    <h1 class="title">Bütün Urunler</h1>
                </div>
            </div>
            <div class="col-lg-6 col-md-4">
                <div class="inner">
                    <div class="bradcrumb-thumb">
                        <img src="assets/images/product/product-45.png" alt="Image">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Breadcrumb Area  -->
<!-- Start Shop Area  -->
<div class="axil-shop-area axil-section-gap bg-color-white">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="axil-shop-top">
                    <div class="row">
                        <div class="col-lg-9">
                            <div class="category-select">
                                @using (Html.BeginForm("product_list","Products"))
                                { 
                              
                                    @Html.DropDownList("brand_id",  null,"Hepsi", new { @class = "single-select", onchange="this.form.submit()"})
                                }
                                    <!-- Start Single Select  -->
                                <select class="single-select">
                                    <option>Ürünler</option>
                                    <option>Telefon</option>

                                </select>
                                <!-- End Single Select  -->
                                <!-- Start Single Select  -->
                                <select class="single-select">
                                    <option>Fiyat Aralıgı</option>
                                    <option>0 - 100</option>

                                </select>

                                <!-- End Single Select  -->

                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="category-select mt_md--10 mt_sm--10 justify-content-lg-end">
                                <!-- Start Single Select  -->
                                <select class="single-select">
                                    <option>En yeniye göre sırala</option>
                                    <option>İsme Gore Sırala</option>
                                    <option>Fiyata Gore</option>

                                </select>
                                <!-- End Single Select  -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row row--15">
           
            @foreach (var item in Model.products)
            {


            <div class="col-xl-3 col-lg-4 col-sm-6">
                <div class="axil-product product-style-one has-color-pick mt--40">
                    <div class="thumbnail">
                        <a href="single-product-3.html">
                            <img src="@item.product_img1" alt="Product Images">
                        </a>

                        <div class="product-hover-action">
                            <ul class="cart-action">
                                <li class="quickview"><a href="#" data-bs-toggle="modal" data-bs-target="#quick-view-modal"><i class="far fa-eye"></i></a></li>

                                <li class="select-option"><a href="@Url.Action("sepete_ekle","Cart",new {id=item.product_id})">Sepete Ekle</a></li>
                                <li class="wishlist"><a href="wishlist.html"><i class="far fa-heart"></i></a></li>
                            </ul>
                        </div>

                    </div>
                    <div class="product-content">
                        <div class="inner">
                            <h5 class="title"><a href="@Url.Action("product_detail","Products",new {id=item.product_id})">@item.product_name</a></h5>
                            <div class="product-price-variant">
                                <span class="price current-price">@item.product_price</span>
                            </div>
                            
                        </div>
                    </div>

                </div>
            </div>
            }
         

        </div>
        <div class="text-center pt--30">
            <a href="#" class="axil-btn btn-bg-lighter btn-load-more">Daha Fazlası</a>
        </div>
    </div>
    <!-- End .container -->
</div>